### PR TITLE
Resets the EOL of all files and removes trailing white spaces.

### PR DESCRIPTION
**Pull request by dietmarw**

### CODE REVIEW

**Comment by dietmarw** [comment]
OK now make sure that all contributors do a `git pull --rebase` on their branches that are not yet merged. Otherwise they might add wrong file endings again.

**Comment by MaximeBaudette** [comment]
Ok great, I'm forwarding the instruction!

**Comment by dietmarw** [comment]
Btw, I would recommend to **always** do a "rebase" pull. The history is much cleaner that way (no multiple merge commits from master in to the various branches). It can be configured so that git does this by default. But it is a matter of taste. 

See also: http://stevenharman.net/git-pull-with-automatic-rebase

**Comment by MaximeBaudette** [comment]
so far it's mostly me who's been sharing and advising on using GIT. I'm clearly not an expert... 
While I understand the fundamental difference between the 2 (merge and rebase), I'm not super confident in using it... (I tried in the past, but wasn't really successful) . 
I understand it makes clearer "timeline", so I'll work on it, but so far I've always understood the messiness of multiple merges...

**Comment by MaximeBaudette** [comment]
@dietmarw 
Seems to have greatly improved or problems, thanks !! 
And rebas is still a bit difficult to understand, but we're trying ;-)

**Pull request merged**
