### PR TITLE
Updates of the transfer functions

### PR DESCRIPTION
**Pull request by tinrabuzin**
#33 #12 The biggest change in this commit are updates to the transfer functions. @AIAitesla this is going to affect you. Instead of putting strange numbers like 1e-9 you can just follow the parameters from PSSE.

### CODE REVIEW

**Comment by MaximeBaudette** [comment]
in the future, try to separate things in different branches, to make it even more readable ;-)

**Comment by AIAitesla** [comment]
@tinrabuzin you said that we could just put the parameters from PSS/E but in the PSS2A model (in the master branch) the transfer function (washout1, washout2,...) still have a parameter as 1/T_wX where X in {1,2,3,4} (see the attached image). These parameters T_wX are 0 so there are several divisions by zero. Please could you take a look on this? Thank you.
pss2a_transferfunctions

**Comment by tinrabuzin** [comment]
@AIAitesla Could you have a look at the model again? And, by the way, you should have created an issue regarding this.

**Comment by AIAitesla** [comment]
Thank you @tinrabuzin! I've seen that you have changed the PSS2A. We will test it and let you know if there are any problems.

**Pull request merged**
