### PR TITLE
Fixing GENROU 

### PR DESCRIPTION
**Pull request by MaximeBaudette**
See #23

### CODE REVIEW

**Comment by AIAitesla** [comment]
@MaximeBaudette we don't see this fixing in the GENROU model in itesla:master.
For instance, we still see 
 parameter Real Epd0=PSIkq0 - (Xpd - Xl)_iq0;
 parameter Real PSIq0=PSIppq0 - Xppq_iq0;

Thank you!

**Comment by MaximeBaudette** [comment]
@AIAitesla 
Indeed, @tinrabuzin did an override of these changes in the merge of his TransferFunctionFix branch. I'll fix it now. Thanks for spotting it ;-D

**Comment by MaximeBaudette** [comment]
@AIAitesla @tinrabuzin @ahsanKTH @lvanfretti @fragom

This is a typical example of why it is always important to first pull the latest commits of the master branch into your own branch, before doing a merge. 

If you don't do so, there can be override.

**Comment by MaximeBaudette** [comment]
@AIAitesla 
Now it should be fine :-D

**Comment by dietmarw** [comment]
Just as a tip, as @MaximeBaudette says, always pull before pushing. You can then sort out conflicts locally. But in order to not get additional merge commits you can tell git to pull with rebase. I've set this as default since I don't like the dummy merge commits which just bring me up to date with "upstream":

```
git config --global  --bool pull.rebase true
```

https://www.atlassian.com/pt/git/tutorial/remote-repositories#!pull

**Pull request merged**
