### PR TITLE
I just wrote "Marcelo was here" in the middle of the code.

### PR DESCRIPTION
**Pull request by marcelofcastro**
The sentence is written on line 188..

### CODE REVIEW

**Comment by MaximeBaudette** [comment]
Ok @marcelofcastro we will review what you did this afternoon

**Comment by MaximeBaudette** [comment]
@tinrabuzin 
Marcelo is working with me, I'll handle all his PR to the repository, ok?

**Comment by dietmarw** [comment]
You know that this PR is invalid right? Dymola has simply stored the **whole** model inside it's `__Dymola_DymolaStoredErrors` annotation. Something that you get when you enter some illegal syntax and say "correct error later".

**Comment by MaximeBaudette** [comment]
@dietmarw 
Yes, I just want to teach this student to do a PR to this repository.

**Comment by tinrabuzin** [comment]
@MaximeBaudette Ok boss!

**Pull request closed without merging**
