### PR TITLE
WindGenerator:

### PR DESCRIPTION
**Pull request by MaximeBaudette**
- moving `/Resources/` folder inside the library's folder
- updating model to reflect the change

### CODE REVIEW

**Comment by dietmarw** [comment]
I would make this more future proof and move the image to:

 `iPSL/Resources/Images/WindGenerator.png`

It is very likely there are other non-modelica resources coming soon. Such as documentations, tutorial PDFs etc.

**Comment by tinrabuzin** [comment]
@MaximeBaudette Resources is maybe the place for tutorial?

**Comment by MaximeBaudette** [comment]
@tinrabuzin I'd prefer we prioritize putting them in the wiki

**Comment by dietmarw** [comment]
Other examples of files that might need putting under `Resources/` in future are scripts, c-files, LICENSE files etc.

**Pull request merged**
